#!/usr/bin/env bash
# Generated by release/build-installer.sh; edit lib/*.sh, not this file.
set -euo pipefail
IFS=$'\n\t'
umask 077
EMBEDDED_TRUSTED_KEYRING_B64=''

# ---- lib/state.sh ----
# shellcheck shell=bash disable=SC2034
# Environment, path-containment, lock, and state helpers.

die() {
  printf 'deepwind-init: %s\n' "$*" >&2
  exit 2
}

info() { printf '%s\n' "$*"; }
warn() { printf 'warning: %s\n' "$*" >&2; }

need_command() {
  command -v "$1" >/dev/null 2>&1 || die "required command not found: $1"
}

sha256_file() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | awk '{print $1}'
  else
    shasum -a 256 "$1" | awk '{print $1}'
  fi
}

configure_paths() {
  CLAUDE_DIR="$HOME/.claude"
  CODEX_DIR="$HOME/.codex"
  FRAMEWORKS_DIR="$HOME/deepwind-frameworks"
  INSTALL_DIR="$HOME/.deepwind/install"
  BIN_DIR="$HOME/.deepwind/bin"
  LOCK_DIR="$HOME/.deepwind-install.lock"
  STATE_FILE="$INSTALL_DIR/state.tsv"
}

assert_safe_home() {
  [ "$(id -u)" -ne 0 ] || die "refusing to run as root"
  [ -n "${HOME:-}" ] || die "HOME is unset"
  case "$HOME" in
    /*) ;;
    *) die "HOME must be an absolute path" ;;
  esac
  case "$HOME" in
    /|/root|*/../*|*/..|*/./*|*/.|*'
'*|*'	'*) die "unsafe HOME: $HOME" ;;
  esac
  [ -d "$HOME" ] || die "HOME is not a directory"
  [ ! -L "$HOME" ] || die "HOME must not be a symlink"
  home_real=$(realpath "$HOME") || die "cannot resolve HOME"
  [ "$home_real" = "${HOME%/}" ] || die "HOME is not canonical"
  if stat -f '%u' "$HOME" >/dev/null 2>&1; then
    home_owner=$(stat -f '%u' "$HOME")
  else
    home_owner=$(stat -c '%u' "$HOME")
  fi
  [ "$home_owner" = "$(id -u)" ] || die "HOME is not owned by the current user"
}

assert_contained_path() {
  candidate=$1
  case "$candidate" in
    "$HOME"/*) ;;
    *) die "path is outside HOME: $candidate" ;;
  esac
  case "$candidate" in *'/../'*|*'/..'|*'/./'*|*'/.'|*'
'*|*'	'*) die "unsafe destination path" ;; esac

  cursor=$candidate
  while [ "$cursor" != "$HOME" ]; do
    if [ -e "$cursor" ] || [ -L "$cursor" ]; then
      [ ! -L "$cursor" ] || die "symlink in managed path: $cursor"
    fi
    cursor=${cursor%/*}
    [ -n "$cursor" ] || die "cannot contain destination path"
  done
}

acquire_lock() {
  assert_contained_path "$LOCK_DIR"
  if ! mkdir "$LOCK_DIR" 2>/dev/null; then
    die "another DeepWind install is active (lock: $LOCK_DIR)"
  fi
  LOCK_HELD=1
}

release_lock() {
  if [ "${LOCK_HELD:-0}" -eq 1 ]; then
    rmdir "$LOCK_DIR" 2>/dev/null || true
    LOCK_HELD=0
  fi
  return 0
}

previous_digest() {
  state_path=$1
  [ -f "$STATE_FILE" ] || return 1
  awk -F '	' -v wanted="$state_path" '$2 == wanted { print $1; found=1; exit } END { if (!found) exit 1 }' "$STATE_FILE"
}

# ---- lib/args.sh ----
# shellcheck shell=bash disable=SC2034
# Argument parsing for the standalone DeepWind installer.

usage() {
  cat <<'EOF'
usage: deepwind-init.sh [options]
  --target claude|codex|both  install target (default: both)
  --version SEMVER            install an exact immutable release
  --channel staging|production
  --dry-run                   verify and print changes without writing
  --check                     verify and report drift without writing
  --force                     replace locally modified managed files
  --skip-hooks                do not install Claude session hooks
  -h, --help
EOF
}

parse_args() {
  TARGET=both
  VERSION=
  CHANNEL=staging
  MODE=install
  FORCE=0
  SKIP_HOOKS=0

  while [ "$#" -gt 0 ]; do
    case "$1" in
      --target)
        [ "$#" -ge 2 ] || die "--target requires a value"
        TARGET=$2
        shift 2
        ;;
      --version)
        [ "$#" -ge 2 ] || die "--version requires a value"
        VERSION=$2
        shift 2
        ;;
      --channel)
        [ "$#" -ge 2 ] || die "--channel requires a value"
        CHANNEL=$2
        shift 2
        ;;
      --dry-run)
        [ "$MODE" = install ] || die "--dry-run and --check are mutually exclusive"
        MODE=dry-run
        shift
        ;;
      --check)
        [ "$MODE" = install ] || die "--dry-run and --check are mutually exclusive"
        MODE=check
        shift
        ;;
      --force)
        FORCE=1
        shift
        ;;
      --skip-hooks)
        SKIP_HOOKS=1
        shift
        ;;
      -h|--help)
        usage
        exit 0
        ;;
      --ref|--configure-mcp|--uninstall)
        die "unsupported option in the safe installer: $1"
        ;;
      *)
        die "unknown option: $1"
        ;;
    esac
  done

  case "$TARGET" in claude|codex|both) ;; *) die "target must be claude, codex, or both" ;; esac
  case "$CHANNEL" in staging|production) ;; *) die "channel must be staging or production" ;; esac
  if [ -n "$VERSION" ]; then
    printf '%s' "$VERSION" | grep -Eq \
      '^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?(\+[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?$' \
      || die "version must be strict semver"
  fi
}

# ---- lib/manifest.sh ----
# shellcheck shell=bash disable=SC2034
# Immutable release resolution, signature verification, and archive validation.

RELEASES_BASE=https://github.com/DeepWindAI/harness/releases
LATEST_RELEASE_URL=https://api.github.com/repos/DeepWindAI/harness/releases/latest

fetch_release_file() {
  release_name=$1
  output_path=$2
  if [ "${DEEPWIND_INSTALL_TESTING:-0}" = 1 ]; then
    [ -n "${DEEPWIND_RELEASE_DIR:-}" ] || die "test release directory is required"
    [ -f "$DEEPWIND_RELEASE_DIR/$release_name" ] || die "fixture asset is missing: $release_name"
    cp "$DEEPWIND_RELEASE_DIR/$release_name" "$output_path"
  else
    curl -fLsS --proto '=https' --tlsv1.2 --connect-timeout 10 --max-time 120 \
      "$RELEASES_BASE/download/v$VERSION/$release_name" -o "$output_path" \
      || die "failed to fetch immutable release asset: $release_name"
  fi
}

resolve_version() {
  [ -z "$VERSION" ] || return 0
  if [ "${DEEPWIND_INSTALL_TESTING:-0}" = 1 ]; then
    [ -f "${DEEPWIND_RELEASE_DIR:-}/deepwind-release-manifest.json" ] \
      || die "fixture manifest is missing"
    VERSION=$(jq -er '.version' "$DEEPWIND_RELEASE_DIR/deepwind-release-manifest.json") \
      || die "fixture manifest has no version"
  else
    latest_json="$WORK_DIR/latest-release.json"
    curl -fLsS --proto '=https' --tlsv1.2 --connect-timeout 10 --max-time 30 \
      "$LATEST_RELEASE_URL" -o "$latest_json" || die "cannot resolve latest immutable release"
    latest_tag=$(jq -er '.tag_name' "$latest_json") || die "latest release has no tag"
    VERSION=${latest_tag#v}
  fi
  printf '%s' "$VERSION" | grep -Eq \
    '^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?(\+[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?$' \
    || die "resolved release is not strict semver"
}

verify_manifest_signature() {
  manifest_path=$1
  signature_path=$2
  [ -n "${EMBEDDED_TRUSTED_KEYRING_B64:-}" ] \
    || die "no trusted release keyring is embedded; release owners must provision it"
  trusted_keyring="$WORK_DIR/trusted-release-keyring.gpg"
  if printf '%s' "$EMBEDDED_TRUSTED_KEYRING_B64" | base64 -d > "$trusted_keyring" 2>/dev/null; then
    :
  elif printf '%s' "$EMBEDDED_TRUSTED_KEYRING_B64" | base64 -D > "$trusted_keyring" 2>/dev/null; then
    :
  else
    die "embedded release keyring is malformed"
  fi
  need_command gpgv
  gpgv --keyring "$trusted_keyring" "$signature_path" "$manifest_path" >/dev/null 2>&1 \
    || die "release manifest signature verification failed"
}

validate_manifest() {
  manifest_path=$1
  jq -e \
    --arg version "$VERSION" --arg tag "v$VERSION" --arg channel "$CHANNEL" '
      .formatVersion == 1 and
      .version == $version and .tag == $tag and .channel == $channel and
      .provenance.repository == "DeepWindAI/harness" and
      (.provenance.revision | test("^[0-9a-f]{7,64}$")) and
      (.endpoint.alias | test("^[a-z0-9][a-z0-9-]{0,62}$")) and
      (.endpoint.url | test("^https://[A-Za-z0-9.-]+(/[^?#]*)?$")) and
      (.archives | length >= 1) and
      ([.archives[].target] | unique | length) == (.archives | length) and
      (.signing.signatureFile == "deepwind-release-manifest.json.asc") and
      (.signing.keyId | test("^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$")) and
      all(.archives[];
        (.target == "claude" or .target == "codex") and
        (.file | test("^deepwind-harness-(claude|codex)-v[0-9A-Za-z.+-]+[.]tar[.]gz$")) and
        (.sha256 | test("^[a-f0-9]{64}$")) and
        (.bytes | type == "number" and . > 0 and . <= 104857600) and
        (.files | type == "array" and length > 0 and length <= 2000 and
          (unique | length) == length) and
        all(.files[];
          type == "string" and length > 0 and length <= 240 and
          test("^[A-Za-z0-9._/@+-]+$") and
          (startswith("/") | not) and
          (test("(^|/)[.][.]?(/|$)") | not)
        )
      )
    ' "$manifest_path" >/dev/null || die "release manifest violates installer limits"
  signing_not_before=$(jq -er '.signing.notBefore' "$manifest_path")
  signing_not_after=$(jq -er '.signing.notAfter' "$manifest_path")
  printf '%s\n%s\n' "$signing_not_before" "$signing_not_after" \
    | grep -Eq '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z$' \
    || die "manifest signing window is not canonical UTC"
  signing_now=$(date -u +%Y-%m-%dT%H:%M:%SZ)
  [[ "$signing_not_before" < "$signing_not_after" ]] \
    && [[ "$signing_now" > "$signing_not_before" || "$signing_now" = "$signing_not_before" ]] \
    && [[ "$signing_now" < "$signing_not_after" || "$signing_now" = "$signing_not_after" ]] \
    || die "manifest signing window is not currently valid"
}

check_free_space() {
  required_bytes=$(jq \
    --arg target "$TARGET" '
      [.archives[]
        | select($target == "both" or .target == $target)
        | .bytes] | add * 4
    ' "$MANIFEST_FILE")
  available_kb=$(df -Pk "$HOME" | awk 'NR == 2 { print $4 }')
  case "$available_kb" in ''|*[!0-9]*) die "cannot determine free space" ;; esac
  available_bytes=$((available_kb * 1024))
  [ "$available_bytes" -ge "$required_bytes" ] \
    || die "insufficient free space for verified staging and rollback"
}

target_selected() {
  selected=$1
  [ "$TARGET" = both ] || [ "$TARGET" = "$selected" ]
}

verify_archive() {
  archive_target=$1
  archive_file=$(jq -er --arg target "$archive_target" \
    '.archives[] | select(.target == $target) | .file' "$MANIFEST_FILE") \
    || die "manifest has no $archive_target archive"
  case "$archive_file" in
    "deepwind-harness-$archive_target-v$VERSION.tar.gz") ;;
    *) die "archive filename does not match target and version" ;;
  esac
  archive_path="$WORK_DIR/$archive_file"
  fetch_release_file "$archive_file" "$archive_path"

  expected_sha=$(jq -r --arg target "$archive_target" \
    '.archives[] | select(.target == $target) | .sha256' "$MANIFEST_FILE")
  expected_bytes=$(jq -r --arg target "$archive_target" \
    '.archives[] | select(.target == $target) | .bytes' "$MANIFEST_FILE")
  [ "$(sha256_file "$archive_path")" = "$expected_sha" ] || die "$archive_target archive digest mismatch"
  actual_bytes=$(wc -c < "$archive_path" | tr -d '[:space:]')
  [ "$actual_bytes" = "$expected_bytes" ] || die "$archive_target archive byte length mismatch"

  listing="$WORK_DIR/$archive_target-files.json"
  tar -tzf "$archive_path" \
    | sed -e 's#^\./##' -e '/^$/d' \
    | LC_ALL=C sort | jq -Rsc 'split("\n") | map(select(length > 0))' > "$listing" \
    || die "cannot list $archive_target archive"
  jq -e --arg target "$archive_target" --slurpfile actual "$listing" \
    '(.archives[] | select(.target == $target) | .files | sort) == $actual[0]' \
    "$MANIFEST_FILE" >/dev/null || die "$archive_target archive member list mismatch"

  tar -tvzf "$archive_path" | awk '
    substr($0, 1, 1) != "-" && substr($0, 1, 1) != "d" { bad=1 }
    END { exit bad }
  ' || die "$archive_target archive contains a link or special file"
  printf '%s\n' "$archive_path"
}

prepare_verified_release() {
  resolve_version
  MANIFEST_FILE="$WORK_DIR/deepwind-release-manifest.json"
  SIGNATURE_FILE="$WORK_DIR/deepwind-release-manifest.json.asc"
  fetch_release_file deepwind-release-manifest.json "$MANIFEST_FILE"
  fetch_release_file deepwind-release-manifest.json.asc "$SIGNATURE_FILE"
  verify_manifest_signature "$MANIFEST_FILE" "$SIGNATURE_FILE"
  validate_manifest "$MANIFEST_FILE"

  CLAUDE_ARCHIVE=
  CODEX_ARCHIVE=
  if target_selected claude; then CLAUDE_ARCHIVE=$(verify_archive claude); fi
  if target_selected codex; then CODEX_ARCHIVE=$(verify_archive codex); fi
  check_free_space
}

# ---- lib/install-target.sh ----
# shellcheck shell=bash
# Convert verified archive members into an allowlisted destination plan.

map_destination() {
  map_target=$1
  member=$2
  case "$map_target:$member" in
    claude:agents/*)
      printf '%s/%s\n' "$CLAUDE_DIR" "$member"
      ;;
    claude:skills/*)
      printf '%s/%s\n' "$CLAUDE_DIR" "$member"
      ;;
    claude:frameworks/*)
      printf '%s/%s\n' "$FRAMEWORKS_DIR" "${member#frameworks/}"
      ;;
    claude:README.md|claude:CLAUDE.md.starter)
      printf '%s/%s\n' "$FRAMEWORKS_DIR" "$member"
      ;;
    claude:payload/hooks/*)
      [ "$SKIP_HOOKS" -eq 0 ] || return 3
      printf '%s/hooks/%s\n' "$CLAUDE_DIR" "${member#payload/hooks/}"
      ;;
    claude:payload/bin/deepwind)
      printf '%s/deepwind\n' "$BIN_DIR"
      ;;
    claude:payload/mcp/*|claude:LICENSE|claude:VERSION)
      printf '%s/share/claude/%s\n' "$INSTALL_DIR" "$member"
      ;;
    codex:plugins/deepwind-harness/*)
      printf '%s/plugins/deepwind-harness/%s\n' "$CODEX_DIR" "${member#plugins/deepwind-harness/}"
      ;;
    codex:codex/agents/*)
      printf '%s/agents/%s\n' "$CODEX_DIR" "${member#codex/agents/}"
      ;;
    codex:LICENSE|codex:VERSION)
      printf '%s/share/codex/%s\n' "$INSTALL_DIR" "$member"
      ;;
    *)
      return 2
      ;;
  esac
}

extract_and_plan_target() {
  plan_target_name=$1
  plan_archive=$2
  extract_root="$WORK_DIR/extracted-$plan_target_name"
  mkdir "$extract_root"
  tar -xzf "$plan_archive" -C "$extract_root" || die "cannot extract $plan_target_name archive"

  jq -r --arg target "$plan_target_name" \
    '.archives[] | select(.target == $target) | .files[]' "$MANIFEST_FILE" \
    | while IFS= read -r member; do
        case "$member" in */) continue ;; esac
        source_path="$extract_root/$member"
        [ -f "$source_path" ] && [ ! -L "$source_path" ] \
          || die "archive member is not a regular file: $member"
        if destination=$(map_destination "$plan_target_name" "$member"); then
          :
        else
          map_status=$?
          [ "$map_status" -eq 3 ] && continue
          die "archive member has no allowlisted destination: $plan_target_name:$member"
        fi
        assert_contained_path "$destination"
        new_digest=$(sha256_file "$source_path")
        action=install
        old_digest=
        if [ -e "$destination" ]; then
          [ -f "$destination" ] && [ ! -L "$destination" ] \
            || die "managed destination is not a regular file: $destination"
          current_digest=$(sha256_file "$destination")
          if [ "$current_digest" = "$new_digest" ]; then
            action=unchanged
          elif old_digest=$(previous_digest "$destination" 2>/dev/null) \
            && [ "$current_digest" = "$old_digest" ]; then
            action=replace
          elif [ "$FORCE" -eq 1 ]; then
            action=replace
          else
            action=preserve
          fi
        fi
        printf '%s\t%s\t%s\t%s\t%s\n' \
          "$plan_target_name" "$source_path" "$destination" "$new_digest" "$action" >> "$PLAN_FILE"
      done
}

plan_release_install() {
  PLAN_FILE="$WORK_DIR/install-plan.tsv"
  : > "$PLAN_FILE"
  if target_selected claude; then extract_and_plan_target claude "$CLAUDE_ARCHIVE"; fi
  if target_selected codex; then extract_and_plan_target codex "$CODEX_ARCHIVE"; fi
  [ -s "$PLAN_FILE" ] || die "selected release contains no installable files"
  duplicate_destination=$(awk -F '	' '{ count[$3]++ } END { for (path in count) if (count[path] > 1) { print path; exit } }' \
    "$PLAN_FILE")
  [ -z "$duplicate_destination" ] \
    || die "multiple archive members map to one destination: $duplicate_destination"
}

print_plan() {
  while IFS='	' read -r plan_target_name source_path destination new_digest action; do
    printf '%-9s %-8s %s\n' "$plan_target_name" "$action" "$destination"
  done < "$PLAN_FILE"
  return 0
}

check_plan() {
  drift=0
  while IFS='	' read -r plan_target_name source_path destination new_digest action; do
    case "$action" in
      unchanged) ;;
      *) drift=1; printf 'drift: %s (%s)\n' "$destination" "$action" ;;
    esac
  done < "$PLAN_FILE"
  return "$drift"
}

# ---- lib/transaction.sh ----
# shellcheck shell=bash disable=SC2034
# Journaled, atomic destination mutation and rollback.

ensure_parent_directories() {
  parent=${1%/*}
  missing=
  cursor=$parent
  while [ "$cursor" != "$HOME" ] && [ ! -d "$cursor" ]; do
    missing="$cursor
$missing"
    cursor=${cursor%/*}
  done
  [ -d "$cursor" ] && [ ! -L "$cursor" ] || die "unsafe destination parent: $cursor"
  printf '%s' "$missing" | while IFS= read -r directory; do
    [ -n "$directory" ] || continue
    mkdir "$directory" || return 1
    printf 'D\t%s\n' "$directory" >> "$JOURNAL_FILE"
  done
}

rollback_transaction() {
  [ -n "${JOURNAL_FILE:-}" ] && [ -f "$JOURNAL_FILE" ] || return 0
  reverse_journal="$WORK_DIR/journal.reverse"
  awk '{ lines[NR]=$0 } END { for (i=NR; i>=1; i--) print lines[i] }' \
    "$JOURNAL_FILE" > "$reverse_journal"
  ROLLBACK_INCOMPLETE=0
  while IFS='	' read -r kind destination backup had_existing; do
    case "$kind" in
      F)
        if [ "$had_existing" = 1 ]; then
          if rm -f "$destination" && mv "$backup" "$destination"; then
            :
          else
            ROLLBACK_INCOMPLETE=1
          fi
        else
          rm -f "$destination" || ROLLBACK_INCOMPLETE=1
        fi
        ;;
      D)
        rmdir "$destination" 2>/dev/null || {
          [ ! -d "$destination" ] || ROLLBACK_INCOMPLETE=1
        }
        ;;
      T)
        rm -f "$destination" || ROLLBACK_INCOMPLETE=1
        ;;
    esac
  done < "$reverse_journal"
  if [ "$ROLLBACK_INCOMPLETE" -ne 0 ]; then
    warn "rollback needs manual repair; recovery journal retained at $WORK_DIR"
    RETAIN_WORK_DIR=1
  fi
  return 0
}

install_one_file() {
  source_path=$1
  destination=$2
  backup_path=
  had_existing=0
  assert_contained_path "$destination"
  ensure_parent_directories "$destination" || die "cannot create destination directory"
  if [ -e "$destination" ]; then
    had_existing=1
    backup_path="$BACKUP_DIR/backup-$MUTATION_COUNT"
    cp -p "$destination" "$backup_path" || die "cannot back up managed file"
  fi
  printf 'F\t%s\t%s\t%s\n' "$destination" "$backup_path" "$had_existing" >> "$JOURNAL_FILE"
  adjacent="$destination.deepwind-new.$$"
  printf 'T\t%s\t\t0\n' "$adjacent" >> "$JOURNAL_FILE"
  cp "$source_path" "$adjacent" || die "cannot stage destination file"
  case "$destination" in
    "$BIN_DIR"/*|"$CLAUDE_DIR/hooks/"*) chmod 755 "$adjacent" ;;
    *) chmod 644 "$adjacent" ;;
  esac
  mv -f "$adjacent" "$destination" || die "cannot atomically replace destination"
  MUTATION_COUNT=$((MUTATION_COUNT + 1))
  if [ "${DEEPWIND_INSTALL_TESTING:-0}" = 1 ] \
    && [ "${DEEPWIND_TEST_INTERRUPT_AFTER_MUTATIONS:-}" = "$MUTATION_COUNT" ]; then
    kill -TERM "$$"
  fi
}

build_next_state() {
  next_state=$1
  : > "$next_state"
  if [ -f "$STATE_FILE" ]; then
    while IFS='	' read -r retained_digest retained_path; do
      if ! awk -F '	' -v wanted="$retained_path" \
        '$3 == wanted { found=1 } END { exit !found }' "$PLAN_FILE"; then
        printf '%s\t%s\n' "$retained_digest" "$retained_path" >> "$next_state"
      fi
    done < "$STATE_FILE"
  fi
  while IFS='	' read -r plan_target_name source_path destination new_digest action; do
    case "$action" in
      preserve)
        if old_digest=$(previous_digest "$destination" 2>/dev/null); then
          printf '%s\t%s\n' "$old_digest" "$destination" >> "$next_state"
        fi
        ;;
      *)
        printf '%s\t%s\n' "$new_digest" "$destination" >> "$next_state"
        ;;
    esac
  done < "$PLAN_FILE"
  LC_ALL=C sort -u "$next_state" -o "$next_state"
}

apply_transaction() {
  acquire_lock
  JOURNAL_FILE="$WORK_DIR/journal.tsv"
  BACKUP_DIR="$WORK_DIR/backups"
  mkdir "$BACKUP_DIR"
  : > "$JOURNAL_FILE"
  MUTATION_COUNT=0
  last_target=

  while IFS='	' read -r plan_target_name source_path destination new_digest action; do
    if [ "$plan_target_name" != "$last_target" ]; then
      last_target=$plan_target_name
      if [ "${DEEPWIND_INSTALL_TESTING:-0}" = 1 ] \
        && [ "${DEEPWIND_TEST_FAIL_TARGET:-}" = "$plan_target_name" ]; then
        die "injected failure for $plan_target_name"
      fi
    fi
    case "$action" in
      install|replace) install_one_file "$source_path" "$destination" ;;
      preserve) warn "preserving locally modified file: $destination" ;;
      unchanged) ;;
      *) die "invalid install action: $action" ;;
    esac
  done < "$PLAN_FILE"

  next_state="$WORK_DIR/state.next"
  build_next_state "$next_state"
  install_one_file "$next_state" "$STATE_FILE"
  TRANSACTION_COMMITTED=1
  release_lock
}

cleanup() {
  status=$?
  trap - EXIT HUP INT TERM
  if [ "${TRANSACTION_COMMITTED:-0}" -ne 1 ]; then
    rollback_transaction
  fi
  release_lock
  if [ "${RETAIN_WORK_DIR:-0}" -ne 1 ] && [ -n "${WORK_DIR:-}" ] && [ -d "$WORK_DIR" ]; then
    find "$WORK_DIR" -depth -type f -exec rm -f {} \;
    find "$WORK_DIR" -depth -type d -exec rmdir {} \; 2>/dev/null || true
  fi
  exit "$status"
}

main() {
  need_command id
  need_command realpath
  need_command stat
  need_command mktemp
  need_command jq
  need_command tar
  need_command awk
  need_command sed
  need_command grep
  need_command curl
  need_command cp
  need_command mv
  need_command chmod
  need_command mkdir
  need_command rmdir
  need_command rm
  need_command find
  need_command df
  need_command sort
  need_command base64
  need_command date
  if ! command -v sha256sum >/dev/null 2>&1; then need_command shasum; fi
  assert_safe_home
  configure_paths
  parse_args "$@"

  WORK_DIR=$(mktemp -d "${TMPDIR:-/tmp}/deepwind-install.XXXXXX") \
    || die "cannot create private staging directory"
  chmod 700 "$WORK_DIR"
  trap cleanup EXIT
  trap 'exit 129' HUP
  trap 'exit 130' INT
  trap 'exit 143' TERM

  prepare_verified_release
  plan_release_install
  case "$MODE" in
    dry-run)
      print_plan
      ;;
    check)
      check_plan
      ;;
    install)
      apply_transaction
      info "DeepWind $VERSION installed for target: $TARGET"
      ;;
  esac
}

main "$@"
