#!/usr/bin/env bash
# Generated by release/build-installer.sh; edit lib/*.sh, not this file.
# shellcheck disable=SC2015
set -euo pipefail
IFS=$'\n\t'
umask 077
EMBEDDED_TRUSTED_KEYRING_B64='mDMEamNa4BYJKwYBBAHaRw8BAQdA4ayBvYfE6pj5WGAZrNPgU317mT8thPdKseQNexIcIV+0LkRlZXBXaW5kIFJlbGVhc2UgU2lnbmluZyA8cmVsZWFzZUBkZWVwd2luZC5haT6ItQQTFgoAXRYhBBNzA9y1SH/4nMYyivz6guC5zD9jBQJqY1rgGxSAAAAAAAQADm1hbnUyLDIuNSsxLjEyLDAsMwIbAwUJAO1OAAULCQgHAgIiAgYVCgkICwIEFgIDAQIeBwIXgAAKCRD8+oLgucw/Y+LIAQCEv/95lajE/Bybf4TL4vV+7tIYKEaikZ7PYTXzUpRJEQEA2NdYMc1pZPozKJ0qdS9afw1SSY1SU87N9FamC2Qr0gc='

# ---- lib/state.sh ----
# shellcheck shell=bash disable=SC2015,SC2034
# Environment, path-containment, lock, and state helpers.

die() {
  printf 'deepwind-init: %s\n' "$*" >&2
  exit 2
}

info() { printf '%s\n' "$*"; }
warn() { printf 'warning: %s\n' "$*" >&2; }

need_command() {
  command -v "$1" >/dev/null 2>&1 || die "required command not found: $1"
}

sha256_file() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | awk '{print $1}'
  else
    shasum -a 256 "$1" | awk '{print $1}'
  fi
}

configure_paths() {
  CLAUDE_DIR="$HOME/.claude"
  CODEX_DIR="$HOME/.codex"
  AGENTS_DIR="$HOME/.agents"
  FRAMEWORKS_DIR="$HOME/deepwind-frameworks"
  INSTALL_DIR="$HOME/.deepwind/install"
  CODEX_MARKETPLACE_DIR="$INSTALL_DIR/share/codex-marketplace"
  BIN_DIR="$HOME/.deepwind/bin"
  LOCK_DIR="$HOME/.deepwind-install.lock"
  STATE_FILE="$INSTALL_DIR/state.tsv"
  RECOVERY_ROOT="$INSTALL_DIR/recovery"
  RECOVERY_STATE_FILE="$INSTALL_DIR/recovery.tsv"
}

assert_safe_home() {
  [ "$(id -u)" -ne 0 ] || die "refusing to run as root"
  [ -n "${HOME:-}" ] || die "HOME is unset"
  case "$HOME" in
    /*) ;;
    *) die "HOME must be an absolute path" ;;
  esac
  case "$HOME" in
    /|/root|*/../*|*/..|*/./*|*/.|*'
'*|*'	'*) die "unsafe HOME: $HOME" ;;
  esac
  [ -d "$HOME" ] || die "HOME is not a directory"
  [ ! -L "$HOME" ] || die "HOME must not be a symlink"
  home_real=$(realpath "$HOME") || die "cannot resolve HOME"
  [ "$home_real" = "${HOME%/}" ] || die "HOME is not canonical"
  if stat -f '%u' "$HOME" >/dev/null 2>&1; then
    home_owner=$(stat -f '%u' "$HOME")
  else
    home_owner=$(stat -c '%u' "$HOME")
  fi
  [ "$home_owner" = "$(id -u)" ] || die "HOME is not owned by the current user"
}

assert_contained_path() {
  candidate=$1
  case "$candidate" in
    "$HOME"/*) ;;
    *) die "path is outside HOME: $candidate" ;;
  esac
  case "$candidate" in *'/../'*|*'/..'|*'/./'*|*'/.'|*'
'*|*'	'*) die "unsafe destination path" ;; esac

  cursor=$candidate
  while [ "$cursor" != "$HOME" ]; do
    if [ -e "$cursor" ] || [ -L "$cursor" ]; then
      [ ! -L "$cursor" ] || die "symlink in managed path: $cursor"
    fi
    cursor=${cursor%/*}
    [ -n "$cursor" ] || die "cannot contain destination path"
  done
}

acquire_lock() {
  assert_contained_path "$LOCK_DIR"
  if ! mkdir "$LOCK_DIR" 2>/dev/null; then
    die "another DeepWind install is active (lock: $LOCK_DIR)"
  fi
  LOCK_HELD=1
}

release_lock() {
  if [ "${LOCK_HELD:-0}" -eq 1 ]; then
    rmdir "$LOCK_DIR" 2>/dev/null || true
    LOCK_HELD=0
  fi
  return 0
}

previous_digest() {
  state_path=$1
  [ -f "$STATE_FILE" ] || return 1
  awk -F '	' -v wanted="$state_path" '$2 == wanted { print $1; found=1; exit } END { if (!found) exit 1 }' "$STATE_FILE"
}

private_mode() {
  if stat -f '%Lp' "$1" >/dev/null 2>&1; then
    stat -f '%Lp' "$1"
  else
    stat -c '%a' "$1"
  fi
}

recovery_destination_allowed() {
  recovery_destination=$1
  case "$recovery_destination" in
    "$CLAUDE_DIR"/agents/*|\
    "$CLAUDE_DIR"/skills/*|\
    "$CLAUDE_DIR"/hooks/*|\
    "$CODEX_DIR"/agents/*|\
    "$CODEX_DIR"/skills/*|\
    "$AGENTS_DIR"/skills/*|\
    "$FRAMEWORKS_DIR"/*|\
    "$BIN_DIR"/*|\
    "$INSTALL_DIR"/share/*)
      return 0
      ;;
    *)
      return 1
      ;;
  esac
}

# Set RECOVERY_STATUS and RECOVERY_COUNT without printing retained paths. The
# state deliberately covers only installer-managed payloads, never Codex auth,
# MCP token caches, or other user configuration.
recovery_state_summary() {
  RECOVERY_STATUS=none
  RECOVERY_COUNT=0
  if [ ! -e "$RECOVERY_STATE_FILE" ]; then
    if [ -d "$RECOVERY_ROOT" ] \
      && [ -n "$(find "$RECOVERY_ROOT" -mindepth 1 -print -quit 2>/dev/null)" ]; then
      RECOVERY_STATUS=attention-required
      return 1
    fi
    return 0
  fi

  [ -f "$RECOVERY_STATE_FILE" ] \
    && [ ! -L "$RECOVERY_STATE_FILE" ] \
    && [ "$(private_mode "$RECOVERY_STATE_FILE")" = 600 ] \
    && [ -d "$RECOVERY_ROOT" ] \
    && [ ! -L "$RECOVERY_ROOT" ] \
    && [ "$(private_mode "$RECOVERY_ROOT")" = 700 ] || {
      RECOVERY_STATUS=attention-required
      return 1
    }

  recovery_valid=1
  recovery_records=0
  while IFS='	' read -r recovery_run recovery_digest recovery_backup recovery_destination recovery_extra; do
    recovery_records=$((recovery_records + 1))
    [ -z "$recovery_extra" ] || recovery_valid=0
    printf '%s\n' "${recovery_run##*/}" \
      | grep -Eq '^[0-9]{8}T[0-9]{6}Z-[0-9]+$' \
      || recovery_valid=0
    case "$recovery_run" in "$RECOVERY_ROOT"/*) ;; *) recovery_valid=0 ;; esac
    [ "${recovery_backup%/*}" = "$recovery_run" ] || recovery_valid=0
    printf '%s\n' "${recovery_backup##*/}" \
      | grep -Eq '^backup-[1-9][0-9]*$' \
      || recovery_valid=0
    case "$recovery_digest" in *[!a-f0-9]*|'') recovery_valid=0 ;; esac
    [ "${#recovery_digest}" -eq 64 ] || recovery_valid=0
    recovery_destination_allowed "$recovery_destination" || recovery_valid=0
    [ -d "$recovery_run" ] \
      && [ ! -L "$recovery_run" ] \
      && [ "$(private_mode "$recovery_run")" = 700 ] \
      && [ -f "$recovery_backup" ] \
      && [ ! -L "$recovery_backup" ] \
      && [ "$(private_mode "$recovery_backup")" = 600 ] \
      && [ "$(sha256_file "$recovery_backup")" = "$recovery_digest" ] \
      || recovery_valid=0
  done < "$RECOVERY_STATE_FILE"

  recovery_files=$(find "$RECOVERY_ROOT" -type f 2>/dev/null | wc -l | tr -d '[:space:]')
  [ "$recovery_records" -gt 0 ] \
    && [ "$recovery_files" = "$recovery_records" ] \
    && [ "$recovery_valid" -eq 1 ] || {
      RECOVERY_STATUS=attention-required
      return 1
    }
  RECOVERY_STATUS=available
  RECOVERY_COUNT=$recovery_records
  return 0
}

check_recovery_backups() {
  if recovery_state_summary; then
    case "$RECOVERY_STATUS" in
      none) printf '%s\n' 'recovery: none retained' ;;
      available) printf 'recovery: %s retained forced-replacement backup(s)\n' "$RECOVERY_COUNT" ;;
    esac
    return 0
  fi
  printf '%s\n' 'recovery: attention-required'
  return 1
}

# ---- lib/args.sh ----
# shellcheck shell=bash disable=SC2034
# Argument parsing for the standalone DeepWind installer.

usage() {
  cat <<'EOF'
usage: deepwind-init.sh [options]
  --target claude|codex|both  install target (default: both)
  --version SEMVER            install an exact immutable release
  --channel staging|production
  --dry-run                   verify and print changes without writing
  --check                     verify and report drift without writing
  --force                     replace locally modified managed files
  --skip-hooks                do not install Claude session hooks
  --enable-codex-plugin       opt in to enabling the verified Codex plugin
  --configure-mcp             interactively configure Codex MCP after install
  --with-bridge               best-effort install the DeepWind bridge CLI (npm) after install
  -h, --help
EOF
}

parse_args() {
  TARGET=both
  VERSION=
  CHANNEL=staging
  MODE=install
  FORCE=0
  SKIP_HOOKS=0
  ENABLE_CODEX_PLUGIN=0
  CONFIGURE_MCP=0
  WITH_BRIDGE=0

  while [ "$#" -gt 0 ]; do
    case "$1" in
      --target)
        [ "$#" -ge 2 ] || die "--target requires a value"
        TARGET=$2
        shift 2
        ;;
      --version)
        [ "$#" -ge 2 ] || die "--version requires a value"
        VERSION=$2
        shift 2
        ;;
      --channel)
        [ "$#" -ge 2 ] || die "--channel requires a value"
        CHANNEL=$2
        shift 2
        ;;
      --dry-run)
        [ "$MODE" = install ] || die "--dry-run and --check are mutually exclusive"
        MODE=dry-run
        shift
        ;;
      --check)
        [ "$MODE" = install ] || die "--dry-run and --check are mutually exclusive"
        MODE=check
        shift
        ;;
      --force)
        FORCE=1
        shift
        ;;
      --skip-hooks)
        SKIP_HOOKS=1
        shift
        ;;
      --enable-codex-plugin)
        ENABLE_CODEX_PLUGIN=1
        shift
        ;;
      --configure-mcp)
        CONFIGURE_MCP=1
        shift
        ;;
      --with-bridge)
        WITH_BRIDGE=1
        shift
        ;;
      -h|--help)
        usage
        exit 0
        ;;
      --ref|--uninstall)
        die "unsupported option in the safe installer: $1"
        ;;
      *)
        die "unknown option: $1"
        ;;
    esac
  done

  case "$TARGET" in claude|codex|both) ;; *) die "target must be claude, codex, or both" ;; esac
  case "$CHANNEL" in staging|production) ;; *) die "channel must be staging or production" ;; esac
  if [ "$CONFIGURE_MCP" -eq 1 ] && [ "$MODE" != install ]; then
    die "--configure-mcp cannot be combined with --dry-run or --check"
  fi
  if [ "$ENABLE_CODEX_PLUGIN" -eq 1 ] && [ "$MODE" != install ]; then
    die "--enable-codex-plugin cannot be combined with --dry-run or --check"
  fi
  if [ "$ENABLE_CODEX_PLUGIN" -eq 1 ] && [ "$TARGET" = claude ]; then
    die "--enable-codex-plugin requires target codex or both"
  fi
  if [ "$WITH_BRIDGE" -eq 1 ] && [ "$MODE" != install ]; then
    die "--with-bridge cannot be combined with --dry-run or --check"
  fi
  if [ -n "$VERSION" ]; then
    printf '%s' "$VERSION" | grep -Eq \
      '^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?(\+[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?$' \
      || die "version must be strict semver"
  fi
}

# ---- lib/manifest.sh ----
# shellcheck shell=bash disable=SC2015,SC2034
# Immutable release resolution, signature verification, and archive validation.

RELEASES_BASE=https://github.com/DeepWindAI/harness/releases
LATEST_RELEASE_URL=https://api.github.com/repos/DeepWindAI/harness/releases/latest

fetch_release_file() {
  release_name=$1
  output_path=$2
  if [ "${DEEPWIND_INSTALL_TESTING:-0}" = 1 ]; then
    [ -n "${DEEPWIND_RELEASE_DIR:-}" ] || die "test release directory is required"
    [ -f "$DEEPWIND_RELEASE_DIR/$release_name" ] || die "fixture asset is missing: $release_name"
    cp "$DEEPWIND_RELEASE_DIR/$release_name" "$output_path"
  else
    curl -fLsS --proto '=https' --tlsv1.2 --connect-timeout 10 --max-time 120 \
      "$RELEASES_BASE/download/v$VERSION/$release_name" -o "$output_path" \
      || die "failed to fetch immutable release asset: $release_name"
  fi
}

resolve_version() {
  [ -z "$VERSION" ] || return 0
  if [ "${DEEPWIND_INSTALL_TESTING:-0}" = 1 ]; then
    [ -f "${DEEPWIND_RELEASE_DIR:-}/deepwind-release-manifest.json" ] \
      || die "fixture manifest is missing"
    VERSION=$(jq -er '.version' "$DEEPWIND_RELEASE_DIR/deepwind-release-manifest.json") \
      || die "fixture manifest has no version"
  else
    latest_json="$WORK_DIR/latest-release.json"
    curl -fLsS --proto '=https' --tlsv1.2 --connect-timeout 10 --max-time 30 \
      "$LATEST_RELEASE_URL" -o "$latest_json" || die "cannot resolve latest immutable release"
    latest_tag=$(jq -er '.tag_name' "$latest_json") || die "latest release has no tag"
    VERSION=${latest_tag#v}
  fi
  printf '%s' "$VERSION" | grep -Eq \
    '^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?(\+[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?$' \
    || die "resolved release is not strict semver"
}

verify_manifest_signature() {
  manifest_path=$1
  signature_path=$2
  [ -n "${EMBEDDED_TRUSTED_KEYRING_B64:-}" ] \
    || die "no trusted release keyring is embedded; release owners must provision it"
  trusted_keyring="$WORK_DIR/trusted-release-keyring.gpg"
  if printf '%s' "$EMBEDDED_TRUSTED_KEYRING_B64" | base64 -d > "$trusted_keyring" 2>/dev/null; then
    :
  elif printf '%s' "$EMBEDDED_TRUSTED_KEYRING_B64" | base64 -D > "$trusted_keyring" 2>/dev/null; then
    :
  else
    die "embedded release keyring is malformed"
  fi
  need_command gpgv
  gpgv --keyring "$trusted_keyring" "$signature_path" "$manifest_path" >/dev/null 2>&1 \
    || die "release manifest signature verification failed"
}

validate_manifest() {
  manifest_path=$1
  jq -e \
    --arg version "$VERSION" --arg tag "v$VERSION" --arg channel "$CHANNEL" '
      .formatVersion == 1 and
      .version == $version and .tag == $tag and .channel == $channel and
      .provenance.repository == "DeepWindAI/harness" and
      (.provenance.revision | test("^[0-9a-f]{7,64}$")) and
      (.endpoint.alias | test("^[a-z0-9][a-z0-9-]{0,62}$")) and
      (.endpoint.url | test("^https://[A-Za-z0-9.-]+(/[^?#]*)?$")) and
      .bootstrap.file == ("deepwind-init-v" + $version + ".sh") and
      (.bootstrap.sha256 | test("^[a-f0-9]{64}$")) and
      (.bootstrap.bytes | type == "number" and . > 0 and . <= 2097152) and
      (.archives | length >= 1) and
      ([.archives[].target] | unique | length) == (.archives | length) and
      (.signing.signatureFile == "deepwind-release-manifest.json.asc") and
      (.signing.keyId | test("^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$")) and
      all(.archives[];
        (.target == "claude" or .target == "codex") and
        (.file | test("^deepwind-harness-(claude|codex)-v[0-9A-Za-z.+-]+[.]tar[.]gz$")) and
        (.sha256 | test("^[a-f0-9]{64}$")) and
        (.bytes | type == "number" and . > 0 and . <= 104857600) and
        (.files | type == "array" and length > 0 and length <= 2000 and
          (unique | length) == length) and
        all(.files[];
          type == "string" and length > 0 and length <= 240 and
          test("^[A-Za-z0-9._/@+-]+$") and
          (startswith("/") | not) and
          (test("(^|/)[.][.]?(/|$)") | not)
        )
      )
    ' "$manifest_path" >/dev/null || die "release manifest violates installer limits"
  signing_not_before=$(jq -er '.signing.notBefore' "$manifest_path")
  signing_not_after=$(jq -er '.signing.notAfter' "$manifest_path")
  printf '%s\n%s\n' "$signing_not_before" "$signing_not_after" \
    | grep -Eq '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z$' \
    || die "manifest signing window is not canonical UTC"
  signing_now=$(date -u +%Y-%m-%dT%H:%M:%SZ)
  [[ "$signing_not_before" < "$signing_not_after" ]] \
    && [[ "$signing_now" > "$signing_not_before" || "$signing_now" = "$signing_not_before" ]] \
    && [[ "$signing_now" < "$signing_not_after" || "$signing_now" = "$signing_not_after" ]] \
    || die "manifest signing window is not currently valid"
}

check_free_space() {
  required_bytes=$(jq \
    --arg target "$TARGET" '
      [.archives[]
        | select($target == "both" or .target == $target)
        | .bytes] | add * 4
    ' "$MANIFEST_FILE")
  available_kb=$(df -Pk "$HOME" | awk 'NR == 2 { print $4 }')
  case "$available_kb" in ''|*[!0-9]*) die "cannot determine free space" ;; esac
  available_bytes=$((available_kb * 1024))
  [ "$available_bytes" -ge "$required_bytes" ] \
    || die "insufficient free space for verified staging and rollback"
}

target_selected() {
  selected=$1
  [ "$TARGET" = both ] || [ "$TARGET" = "$selected" ]
}

verify_archive() {
  archive_target=$1
  archive_file=$(jq -er --arg target "$archive_target" \
    '.archives[] | select(.target == $target) | .file' "$MANIFEST_FILE") \
    || die "manifest has no $archive_target archive"
  case "$archive_file" in
    "deepwind-harness-$archive_target-v$VERSION.tar.gz") ;;
    *) die "archive filename does not match target and version" ;;
  esac
  archive_path="$WORK_DIR/$archive_file"
  fetch_release_file "$archive_file" "$archive_path"

  expected_sha=$(jq -r --arg target "$archive_target" \
    '.archives[] | select(.target == $target) | .sha256' "$MANIFEST_FILE")
  expected_bytes=$(jq -r --arg target "$archive_target" \
    '.archives[] | select(.target == $target) | .bytes' "$MANIFEST_FILE")
  [ "$(sha256_file "$archive_path")" = "$expected_sha" ] || die "$archive_target archive digest mismatch"
  actual_bytes=$(wc -c < "$archive_path" | tr -d '[:space:]')
  [ "$actual_bytes" = "$expected_bytes" ] || die "$archive_target archive byte length mismatch"

  listing="$WORK_DIR/$archive_target-files.json"
  tar -tzf "$archive_path" \
    | sed -e 's#^\./##' -e '/^$/d' \
    | LC_ALL=C sort | jq -Rsc 'split("\n") | map(select(length > 0))' > "$listing" \
    || die "cannot list $archive_target archive"
  jq -e --arg target "$archive_target" --slurpfile actual "$listing" \
    '(.archives[] | select(.target == $target) | .files | sort) == $actual[0]' \
    "$MANIFEST_FILE" >/dev/null || die "$archive_target archive member list mismatch"

  tar -tvzf "$archive_path" | awk '
    substr($0, 1, 1) != "-" && substr($0, 1, 1) != "d" { bad=1 }
    END { exit bad }
  ' || die "$archive_target archive contains a link or special file"
  printf '%s\n' "$archive_path"
}

prepare_verified_release() {
  resolve_version
  MANIFEST_FILE="$WORK_DIR/deepwind-release-manifest.json"
  SIGNATURE_FILE="$WORK_DIR/deepwind-release-manifest.json.asc"
  fetch_release_file deepwind-release-manifest.json "$MANIFEST_FILE"
  fetch_release_file deepwind-release-manifest.json.asc "$SIGNATURE_FILE"
  verify_manifest_signature "$MANIFEST_FILE" "$SIGNATURE_FILE"
  validate_manifest "$MANIFEST_FILE"

  CLAUDE_ARCHIVE=
  CODEX_ARCHIVE=
  if target_selected claude; then CLAUDE_ARCHIVE=$(verify_archive claude); fi
  if target_selected codex; then CODEX_ARCHIVE=$(verify_archive codex); fi
  check_free_space
}

# ---- lib/install-target.sh ----
# shellcheck shell=bash disable=SC2015
# Convert verified archive members into an allowlisted destination plan.

map_destination() {
  map_target=$1
  member=$2
  case "$map_target:$member" in
    claude:agents/*)
      printf '%s/%s\n' "$CLAUDE_DIR" "$member"
      ;;
    claude:skills/*)
      printf '%s/%s\n' "$CLAUDE_DIR" "$member"
      ;;
    claude:frameworks/*)
      printf '%s/%s\n' "$FRAMEWORKS_DIR" "${member#frameworks/}"
      ;;
    claude:README.md|claude:CLAUDE.md.starter)
      printf '%s/%s\n' "$FRAMEWORKS_DIR" "$member"
      ;;
    claude:payload/hooks/*)
      [ "$SKIP_HOOKS" -eq 0 ] || return 3
      printf '%s/hooks/%s\n' "$CLAUDE_DIR" "${member#payload/hooks/}"
      ;;
    claude:payload/bin/deepwind)
      printf '%s/deepwind\n' "$BIN_DIR"
      ;;
    claude:payload/bin/check-sensitive-review.sh|\
    claude:payload/bin/guarded-merge.sh|\
    claude:payload/bin/agent-approve.sh)
      # Merge-gate helper scripts — installed next to `deepwind` so guarded-merge.sh
      # finds check-sensitive-review.sh as a sibling and the hook can call them by
      # absolute path. Executable via the $BIN_DIR/* chmod-755 arm in transaction.sh.
      printf '%s/%s\n' "$BIN_DIR" "${member#payload/bin/}"
      ;;
    claude:payload/mcp/*|claude:LICENSE|claude:VERSION)
      printf '%s/share/claude/%s\n' "$INSTALL_DIR" "$member"
      ;;
    codex:plugins/deepwind-harness/*)
      printf '%s/plugins/deepwind-harness/%s\n' "$CODEX_MARKETPLACE_DIR" "${member#plugins/deepwind-harness/}"
      ;;
    codex:.agents/plugins/marketplace.json)
      printf '%s/.agents/plugins/marketplace.json\n' "$CODEX_MARKETPLACE_DIR"
      ;;
    codex:codex/agents/frontend-developer.toml|\
    codex:codex/agents/harness-coordinator.toml|\
    codex:codex/agents/harness-planner.toml|\
    codex:codex/agents/security-auditor.toml)
      printf '%s/agents/%s\n' "$CODEX_DIR" "${member#codex/agents/}"
      ;;
    codex:LICENSE|codex:VERSION)
      printf '%s/share/codex/%s\n' "$INSTALL_DIR" "$member"
      ;;
    *)
      return 2
      ;;
  esac
}

codex_role_is_tracked() {
  case "$1" in
    frontend-developer.toml|\
    harness-coordinator.toml|\
    harness-planner.toml|\
    security-auditor.toml) return 0 ;;
    *) return 1 ;;
  esac
}

plan_managed_file() {
  managed_target=$1
  managed_source=$2
  managed_destination=$3
  managed_state_path=$4
  managed_force=$5
  assert_contained_path "$managed_destination"
  new_digest=$(sha256_file "$managed_source")
  action=install
  old_digest=
  if [ -e "$managed_destination" ]; then
    [ -f "$managed_destination" ] && [ ! -L "$managed_destination" ] \
      || die "managed destination is not a regular file: $managed_destination"
    current_digest=$(sha256_file "$managed_destination")
    if [ "$current_digest" = "$new_digest" ]; then
      action=unchanged
    elif [ -f "$managed_state_path" ] \
      && old_digest=$(awk -F '	' -v wanted="$managed_destination" \
        '$2 == wanted { print $1; found=1; exit } END { if (!found) exit 1 }' \
        "$managed_state_path") \
      && [ "$current_digest" = "$old_digest" ]; then
      action=replace
    elif [ "$managed_force" -eq 1 ]; then
      action=force-replace
    else
      action=preserve
    fi
  fi
  printf '%s\t%s\t%s\t%s\t%s\n' \
    "$managed_target" "$managed_source" "$managed_destination" "$new_digest" "$action" >> "$PLAN_FILE"
}

# Plan the complete, release-tracked Codex role pack. Mutation remains owned by
# apply_transaction so roles share the installer's journal, backup, and state.
install_codex_roles() {
  role_source_dir=$1
  role_destination_dir=$2
  role_state_path=$3
  role_force=$4
  case "$role_force" in 0|1) ;; *) die "invalid Codex role force mode" ;; esac

  while IFS= read -r role_file; do
    role_source="$role_source_dir/$role_file"
    [ -f "$role_source" ] && [ ! -L "$role_source" ] \
      || die "tracked Codex role is missing or unsafe: $role_file"
    plan_managed_file \
      codex \
      "$role_source" \
      "$role_destination_dir/$role_file" \
      "$role_state_path" \
      "$role_force"
  done <<'EOF'
frontend-developer.toml
harness-coordinator.toml
harness-planner.toml
security-auditor.toml
EOF
}

extract_and_plan_target() {
  plan_target_name=$1
  plan_archive=$2
  extract_root="$WORK_DIR/extracted-$plan_target_name"
  mkdir "$extract_root"
  tar -xzf "$plan_archive" -C "$extract_root" || die "cannot extract $plan_target_name archive"

  jq -r --arg target "$plan_target_name" \
    '.archives[] | select(.target == $target) | .files[]' "$MANIFEST_FILE" \
    | while IFS= read -r member; do
        case "$member" in */) continue ;; esac
        source_path="$extract_root/$member"
        [ -f "$source_path" ] && [ ! -L "$source_path" ] \
          || die "archive member is not a regular file: $member"
        if [ "$plan_target_name" = codex ]; then
          case "$member" in
            codex/agents/*)
              role_file=${member#codex/agents/}
              case "$role_file" in */*) die "untracked Codex role: $member" ;; esac
              codex_role_is_tracked "$role_file" \
                || die "untracked Codex role: $member"
              continue
              ;;
          esac
        fi
        if destination=$(map_destination "$plan_target_name" "$member"); then
          :
        else
          map_status=$?
          [ "$map_status" -eq 3 ] && continue
          die "archive member has no allowlisted destination: $plan_target_name:$member"
        fi
        plan_managed_file \
          "$plan_target_name" "$source_path" "$destination" "$STATE_FILE" "$FORCE"
      done
  if [ "$plan_target_name" = codex ]; then
    install_codex_roles \
      "$extract_root/codex/agents" "$CODEX_DIR/agents" "$STATE_FILE" "$FORCE"
  fi
}

plan_release_install() {
  PLAN_FILE="$WORK_DIR/install-plan.tsv"
  : > "$PLAN_FILE"
  if target_selected claude; then extract_and_plan_target claude "$CLAUDE_ARCHIVE"; fi
  if target_selected codex; then extract_and_plan_target codex "$CODEX_ARCHIVE"; fi
  [ -s "$PLAN_FILE" ] || die "selected release contains no installable files"
  duplicate_destination=$(awk -F '	' '{ count[$3]++ } END { for (path in count) if (count[path] > 1) { print path; exit } }' \
    "$PLAN_FILE")
  [ -z "$duplicate_destination" ] \
    || die "multiple archive members map to one destination: $duplicate_destination"
}

print_plan() {
  while IFS='	' read -r plan_target_name source_path destination new_digest action; do
    printf '%-9s %-8s %s\n' "$plan_target_name" "$action" "$destination"
  done < "$PLAN_FILE"
  print_merge_gate_plan
  return 0
}

check_plan() {
  drift=0
  while IFS='	' read -r plan_target_name source_path destination new_digest action; do
    case "$action" in
      unchanged) ;;
      *) drift=1; printf 'drift: %s (%s)\n' "$destination" "$action" ;;
    esac
  done < "$PLAN_FILE"
  check_merge_gate_registration || drift=1
  check_recovery_backups || drift=1
  if target_selected codex; then
    print_codex_plugin_status || drift=1
  fi
  return "$drift"
}

# ---- lib/transaction.sh ----
# shellcheck shell=bash disable=SC2015,SC2034
# Journaled, atomic destination mutation and rollback.

ensure_parent_directories() {
  parent=${1%/*}
  missing=
  cursor=$parent
  while [ "$cursor" != "$HOME" ] && [ ! -d "$cursor" ]; do
    missing="$cursor
$missing"
    cursor=${cursor%/*}
  done
  [ -d "$cursor" ] && [ ! -L "$cursor" ] || die "unsafe destination parent: $cursor"
  printf '%s' "$missing" | while IFS= read -r directory; do
    [ -n "$directory" ] || continue
    mkdir "$directory" || return 1
    printf 'D\t%s\n' "$directory" >> "$JOURNAL_FILE"
  done
}

rollback_transaction() {
  [ -n "${JOURNAL_FILE:-}" ] && [ -f "$JOURNAL_FILE" ] || return 0
  reverse_journal="$WORK_DIR/journal.reverse"
  awk '{ lines[NR]=$0 } END { for (i=NR; i>=1; i--) print lines[i] }' \
    "$JOURNAL_FILE" > "$reverse_journal"
  ROLLBACK_INCOMPLETE=0
  while IFS='	' read -r kind destination backup had_existing; do
    case "$kind" in
      F)
        if [ "$had_existing" = 1 ]; then
          if rm -f "$destination" && mv "$backup" "$destination"; then
            :
          else
            ROLLBACK_INCOMPLETE=1
          fi
        else
          rm -f "$destination" || ROLLBACK_INCOMPLETE=1
        fi
        ;;
      D)
        rmdir "$destination" 2>/dev/null || {
          [ ! -d "$destination" ] || ROLLBACK_INCOMPLETE=1
        }
        ;;
      T)
        rm -f "$destination" || ROLLBACK_INCOMPLETE=1
        ;;
      R)
        # Retired plugin aliases have no current destination. Restore one only
        # when a failed transaction did not create anything in its place.
        if [ ! -e "$destination" ] && [ ! -L "$destination" ] \
          && mv "$backup" "$destination"; then
          :
        else
          ROLLBACK_INCOMPLETE=1
        fi
        ;;
    esac
  done < "$reverse_journal"
  if [ "$ROLLBACK_INCOMPLETE" -ne 0 ]; then
    warn "rollback needs manual repair; recovery journal retained at $WORK_DIR"
    RETAIN_WORK_DIR=1
  fi
  return 0
}

retired_codex_plugin_skill_path() {
  case "$1" in
    "$CODEX_MARKETPLACE_DIR"/plugins/deepwind-harness/skills/harness-prep|\
    "$CODEX_MARKETPLACE_DIR"/plugins/deepwind-harness/skills/harness-planner|\
    "$CODEX_MARKETPLACE_DIR"/plugins/deepwind-harness/skills/harness-coordinator|\
    "$CODEX_MARKETPLACE_DIR"/plugins/deepwind-harness/skills/harness-discipline)
      return 0
      ;;
    *) return 1 ;;
  esac
}

retired_codex_plugin_skill_file() {
  retired_codex_plugin_skill_path "${1%/SKILL.md}"
}

retire_codex_plugin_skill_aliases() {
  # Releases before the formal catalog placed unprefixed aliases inside the
  # plugin. Retire only those exact installer-owned directories, never a
  # wildcard or a user-provided skill, so upgrades expose every skill once.
  for retired_name in harness-prep harness-planner harness-coordinator harness-discipline; do
    retired_path="$CODEX_MARKETPLACE_DIR/plugins/deepwind-harness/skills/$retired_name"
    retired_codex_plugin_skill_path "$retired_path" \
      || die "unsafe retired Codex plugin skill path"
    [ ! -L "$retired_path" ] || die "symlink in retired Codex plugin skill path: $retired_path"
    [ ! -e "$retired_path" ] || {
      [ -d "$retired_path" ] || die "retired Codex plugin skill is not a directory: $retired_path"
      retired_backup="$BACKUP_DIR/retired-codex-skill-$retired_name"
      mv "$retired_path" "$retired_backup" \
        || die "cannot retire obsolete Codex plugin skill: $retired_name"
      printf 'R\t%s\t%s\t1\n' "$retired_path" "$retired_backup" >> "$JOURNAL_FILE"
    }
  done
}

install_one_file() {
  source_path=$1
  destination=$2
  retain_forced_backup=${3:-0}
  backup_path=
  had_existing=0
  assert_contained_path "$destination"
  ensure_parent_directories "$destination" || die "cannot create destination directory"
  if [ -e "$destination" ]; then
    had_existing=1
    backup_path="$BACKUP_DIR/backup-$MUTATION_COUNT"
    cp -p "$destination" "$backup_path" || die "cannot back up managed file"
    if [ "$retain_forced_backup" -eq 1 ]; then
      recovery_destination_allowed "$destination" \
        || die "forced replacement is not an allowlisted recovery destination"
      backup_digest=$(sha256_file "$backup_path")
      printf '%s\t%s\t%s\n' "$backup_digest" "$backup_path" "$destination" \
        >> "$PENDING_FORCE_BACKUPS"
    fi
  fi
  printf 'F\t%s\t%s\t%s\n' "$destination" "$backup_path" "$had_existing" >> "$JOURNAL_FILE"
  adjacent="$destination.deepwind-new.$$"
  printf 'T\t%s\t\t0\n' "$adjacent" >> "$JOURNAL_FILE"
  cp "$source_path" "$adjacent" || die "cannot stage destination file"
  case "$destination" in
    "$BIN_DIR"/*|"$CLAUDE_DIR/hooks/"*) chmod 755 "$adjacent" ;;
    "$RECOVERY_ROOT"/*|"$RECOVERY_STATE_FILE") chmod 600 "$adjacent" ;;
    *) chmod 644 "$adjacent" ;;
  esac
  mv -f "$adjacent" "$destination" || die "cannot atomically replace destination"
  MUTATION_COUNT=$((MUTATION_COUNT + 1))
  if [ "${DEEPWIND_INSTALL_TESTING:-0}" = 1 ] \
    && [ "${DEEPWIND_TEST_INTERRUPT_AFTER_MUTATIONS:-}" = "$MUTATION_COUNT" ]; then
    kill -TERM "$$"
  fi
}

persist_forced_backups() {
  [ -s "$PENDING_FORCE_BACKUPS" ] || return 0
  recovery_stamp=$(date -u +%Y%m%dT%H%M%SZ)
  recovery_run="$RECOVERY_ROOT/$recovery_stamp-$$"
  assert_contained_path "$recovery_run"
  [ ! -e "$recovery_run" ] || die "recovery run path already exists"

  recovery_next="$WORK_DIR/recovery.next"
  if [ -f "$RECOVERY_STATE_FILE" ]; then
    cp "$RECOVERY_STATE_FILE" "$recovery_next" \
      || die "cannot stage recovery state"
  else
    : > "$recovery_next"
  fi

  recovery_index=0
  while IFS='	' read -r recovery_digest rollback_backup recovery_destination; do
    recovery_index=$((recovery_index + 1))
    retained_backup="$recovery_run/backup-$recovery_index"
    install_one_file "$rollback_backup" "$retained_backup" 0
    [ "$(sha256_file "$retained_backup")" = "$recovery_digest" ] \
      || die "retained recovery backup digest mismatch"
    printf '%s\t%s\t%s\t%s\n' \
      "$recovery_run" "$recovery_digest" "$retained_backup" "$recovery_destination" \
      >> "$recovery_next"
  done < "$PENDING_FORCE_BACKUPS"

  install_one_file "$recovery_next" "$RECOVERY_STATE_FILE" 0
}

build_next_state() {
  next_state=$1
  : > "$next_state"
  if [ -f "$STATE_FILE" ]; then
    while IFS='	' read -r retained_digest retained_path; do
      retired_codex_plugin_skill_file "$retained_path" && continue
      if ! awk -F '	' -v wanted="$retained_path" \
        '$3 == wanted { found=1 } END { exit !found }' "$PLAN_FILE"; then
        printf '%s\t%s\n' "$retained_digest" "$retained_path" >> "$next_state"
      fi
    done < "$STATE_FILE"
  fi
  while IFS='	' read -r plan_target_name source_path destination new_digest action; do
    case "$action" in
      preserve)
        if old_digest=$(previous_digest "$destination" 2>/dev/null); then
          printf '%s\t%s\n' "$old_digest" "$destination" >> "$next_state"
        fi
        ;;
      *)
        printf '%s\t%s\n' "$new_digest" "$destination" >> "$next_state"
        ;;
    esac
  done < "$PLAN_FILE"
  LC_ALL=C sort -u "$next_state" -o "$next_state"
}

apply_transaction() {
  acquire_lock
  recovery_state_summary \
    || die "retained recovery state requires attention before installation"
  JOURNAL_FILE="$WORK_DIR/journal.tsv"
  BACKUP_DIR="$WORK_DIR/backups"
  mkdir "$BACKUP_DIR"
  : > "$JOURNAL_FILE"
  PENDING_FORCE_BACKUPS="$WORK_DIR/forced-backups.tsv"
  : > "$PENDING_FORCE_BACKUPS"
  MUTATION_COUNT=0
  last_target=

  if target_selected codex; then
    retire_codex_plugin_skill_aliases
  fi

  while IFS='	' read -r plan_target_name source_path destination new_digest action; do
    if [ "$plan_target_name" != "$last_target" ]; then
      last_target=$plan_target_name
      if [ "${DEEPWIND_INSTALL_TESTING:-0}" = 1 ] \
        && [ "${DEEPWIND_TEST_FAIL_TARGET:-}" = "$plan_target_name" ]; then
        die "injected failure for $plan_target_name"
      fi
    fi
    case "$action" in
      install|replace) install_one_file "$source_path" "$destination" 0 ;;
      force-replace) install_one_file "$source_path" "$destination" 1 ;;
      preserve) warn "preserving locally modified file: $destination" ;;
      unchanged) ;;
      *) die "invalid install action: $action" ;;
    esac
  done < "$PLAN_FILE"

  # Register the merge-guard hook in settings.json (journaled via install_one_file, so a
  # later failure rolls back the prior settings.json). No-op unless the hook is installed
  # and not already registered. Runs before the state write so it shares this transaction.
  register_merge_gate_hook

  next_state="$WORK_DIR/state.next"
  build_next_state "$next_state"
  install_one_file "$next_state" "$STATE_FILE" 0
  persist_forced_backups
  TRANSACTION_COMMITTED=1
  release_lock
}

# ---- lib/settings.sh ----
# shellcheck shell=bash disable=SC2015,SC2034
# Register the merge-guard PreToolUse[Bash] hook in ~/.claude/settings.json.
#
# Claude Code only fires hooks that are DECLARED in settings.json — copying the hook
# file into ~/.claude/hooks/ is not enough. This unit adds one idempotent PreToolUse
# entry pointing at the installed pre-bash-merge-guard.sh so the gate actually enforces.
#
# Safety model: this is the ONLY place the installer edits a user-owned file it does not
# fully own. It therefore:
#   - only runs when the hook is actually part of this install (SKIP_HOOKS=0, claude
#     target, and the hook file is in the plan),
#   - is a no-op when the command is already registered (preserves the user's formatting),
#   - never touches a symlinked / non-regular settings.json or one that is not valid JSON
#     (warns and skips — the user registers manually),
#   - performs the write through install_one_file, so the existing journal backs up the
#     prior settings.json and rollback restores it byte-for-byte on any later failure.
# settings.json is deliberately NOT added to the managed state list: the installer owns
# only this one hook fragment, not the whole file, so it must not drift-track it.

merge_gate_settings_file() { printf '%s/settings.json\n' "$CLAUDE_DIR"; }
merge_gate_hook_command() { printf '%s/hooks/pre-bash-merge-guard.sh\n' "$CLAUDE_DIR"; }

# jq predicate: is $cmd already present as a PreToolUse command hook?
merge_gate_hook_registered() {
  mgr_file=$1
  mgr_cmd=$2
  [ -f "$mgr_file" ] && [ ! -L "$mgr_file" ] || return 1
  jq -e --arg cmd "$mgr_cmd" \
    '[ (.hooks.PreToolUse // [])[]? | (.hooks // [])[]? | .command? ] | any(. == $cmd)' \
    "$mgr_file" >/dev/null 2>&1
}

# Is the hook file part of THIS install plan (so registering it makes sense)?
merge_gate_hook_in_plan() {
  [ -n "${PLAN_FILE:-}" ] && [ -f "$PLAN_FILE" ] || return 1
  awk -F '\t' -v want="$CLAUDE_DIR/hooks/pre-bash-merge-guard.sh" \
    '$3 == want { found = 1 } END { exit !found }' "$PLAN_FILE"
}

# Registration disposition for reporting (dry-run/check) and gating (install):
#   0 = a clean registration WOULD occur (hook in plan, not yet registered, file mergeable)
#   1 = nothing to do (skip-hooks, non-claude, hook not in plan, or already registered)
#   2 = hook is in plan + unregistered, but settings.json is unmergeable → MANUAL needed
merge_gate_registration_status() {
  [ "${SKIP_HOOKS:-0}" -eq 0 ] || return 1
  target_selected claude || return 1
  merge_gate_hook_in_plan || return 1
  mgr_settings=$(merge_gate_settings_file)
  mgr_cmd=$(merge_gate_hook_command)
  merge_gate_hook_registered "$mgr_settings" "$mgr_cmd" && return 1
  if [ -e "$mgr_settings" ]; then
    if [ -L "$mgr_settings" ] || [ ! -f "$mgr_settings" ]; then return 2; fi
    jq -e . "$mgr_settings" >/dev/null 2>&1 || return 2
  fi
  return 0
}

# Print a plan line describing the settings.json disposition (dry-run parity with print_plan).
# merge_gate_registration_status returns non-zero for the normal no-op/manual dispositions,
# so it MUST be called in a tested context (`|| ...`) — a bare call would abort the whole
# installer under `set -euo pipefail` before $? is read.
print_merge_gate_plan() {
  mgp_status=0
  merge_gate_registration_status || mgp_status=$?
  case "$mgp_status" in
    0) printf '%-9s %-8s %s\n' claude register "$(merge_gate_settings_file) (PreToolUse[Bash] merge-guard)" ;;
    2) printf '%-9s %-8s %s\n' claude manual "$(merge_gate_settings_file) (unparseable — register merge-guard by hand)" ;;
    *) : ;;
  esac
  return 0
}

# Report settings-registration drift for check_plan. Returns 1 (drift) if action needed.
# Same errexit-safety requirement as above — capture status via `|| ...`, never bare.
check_merge_gate_registration() {
  cmr_status=0
  merge_gate_registration_status || cmr_status=$?
  case "$cmr_status" in
    0) printf 'drift: %s (register merge-guard PreToolUse[Bash] hook)\n' "$(merge_gate_settings_file)"; return 1 ;;
    2) printf 'drift: %s (unparseable settings.json — register merge-guard by hand)\n' "$(merge_gate_settings_file)"; return 1 ;;
    *) return 0 ;;
  esac
}

# Perform the registration inside the journaled transaction (install mode only).
# Must be called from apply_transaction after JOURNAL_FILE/BACKUP_DIR/MUTATION_COUNT
# are initialised and before TRANSACTION_COMMITTED, so a later failure rolls it back.
register_merge_gate_hook() {
  # Tested context (`|| ...`) is REQUIRED: merge_gate_registration_status returns non-zero
  # for the common dispositions (already registered, --skip-hooks, non-claude target,
  # unparseable settings.json). A bare call would trip `set -e` and abort + roll back the
  # entire install before $? is read — including on every idempotent re-run / upgrade.
  reg_status=0
  merge_gate_registration_status || reg_status=$?
  if [ "$reg_status" -eq 2 ]; then
    warn "settings.json is not mergeable JSON; skipping merge-guard hook registration (register it by hand)"
    return 0
  fi
  [ "$reg_status" -eq 0 ] || return 0

  reg_settings=$(merge_gate_settings_file)
  reg_cmd=$(merge_gate_hook_command)
  if [ -e "$reg_settings" ]; then
    reg_current=$(cat "$reg_settings")
  else
    reg_current='{}'
  fi

  reg_merged="$WORK_DIR/settings.merged.json"
  if ! printf '%s' "$reg_current" | jq --arg cmd "$reg_cmd" '
      . as $root
      | ($root.hooks // {}) as $h
      | ($h.PreToolUse // []) as $pre
      | ( [ ($pre[]?) | (.hooks // [])[]? | .command? ] | any(. == $cmd) ) as $present
      | if $present then $root
        else $root
          | .hooks = ($h | .PreToolUse = ($pre + [ {matcher: "Bash", hooks: [ {type: "command", command: $cmd} ]} ]))
        end
    ' > "$reg_merged" 2>/dev/null; then
    warn "could not merge merge-guard hook into settings.json; skipping registration"
    return 0
  fi

  # Sanity: the merged file must be valid JSON AND now contain our command.
  merge_gate_hook_registered "$reg_merged" "$reg_cmd" \
    || { warn "merge-guard registration sanity check failed; skipping"; return 0; }

  install_one_file "$reg_merged" "$reg_settings" 0
  info "registered the merge-guard PreToolUse[Bash] hook in $reg_settings"
}

# Concise post-install note about the merge-gate (printed after "installed for target"
# by the installer's main flow). Prints only when the gate is actually active — the
# hook installed for the claude target and registered — so re-runs and --skip-hooks
# installs that leave it off don't advertise it.
merge_gate_summary() {
  [ "${SKIP_HOOKS:-0}" -eq 0 ] || return 0
  target_selected claude || return 0
  mgs_settings=$(merge_gate_settings_file)
  mgs_cmd=$(merge_gate_hook_command)
  merge_gate_hook_registered "$mgs_settings" "$mgs_cmd" || return 0
  info ""
  info "Merge-gate active: blocks self-merging an unreviewed, security-sensitive PR."
  info "  Sanctioned merge:   $BIN_DIR/guarded-merge.sh <PR>"
  info "  Raw 'gh pr merge' is gated by the PreToolUse hook (bypass: MERGE_GUARD=0)."
  info "  Each repo lists its sensitive paths in .deepwind/sensitive-paths (default if absent)."
}

# ---- lib/codex-plugin.sh ----
# shellcheck shell=bash disable=SC2034
# Opt-in lifecycle for the verified, release-contained Codex plugin.
#
# Only the Codex CLI owns Codex configuration and cache mutations. This unit
# never edits config.toml or a personal marketplace catalog directly, and it
# refuses to replace a configured marketplace that points anywhere except the
# verified installer-managed release root.

DEEPWIND_CODEX_PLUGIN_ID=deepwind-harness@deepwind
DEEPWIND_CODEX_MARKETPLACE=deepwind

inspect_codex_plugin() {
  CODEX_PLUGIN_STATUS=cli-unavailable
  command -v codex >/dev/null 2>&1 || return 0

  marketplace_json="$WORK_DIR/codex-marketplaces.json"
  if ! codex plugin marketplace list --json > "$marketplace_json" 2>/dev/null; then
    CODEX_PLUGIN_STATUS=command-error
    return 0
  fi
  if ! jq -e '.marketplaces | type == "array"' "$marketplace_json" >/dev/null 2>&1; then
    CODEX_PLUGIN_STATUS=command-error
    return 0
  fi

  marketplace_count=$(jq -r --arg name "$DEEPWIND_CODEX_MARKETPLACE" \
    '[.marketplaces[] | select(.name == $name)] | length' "$marketplace_json")
  if [ "$marketplace_count" -eq 0 ]; then
    CODEX_PLUGIN_STATUS=marketplace-not-configured
    return 0
  fi
  if [ "$marketplace_count" -ne 1 ] || ! jq -e \
    --arg name "$DEEPWIND_CODEX_MARKETPLACE" \
    --arg source "$CODEX_MARKETPLACE_DIR" '
      any(.marketplaces[];
        .name == $name and
        .marketplaceSource.sourceType == "local" and
        .marketplaceSource.source == $source and
        .root == $source
      )
    ' "$marketplace_json" >/dev/null; then
    CODEX_PLUGIN_STATUS=marketplace-conflict
    return 0
  fi

  plugin_json="$WORK_DIR/codex-plugins.json"
  if ! codex plugin list --json > "$plugin_json" 2>/dev/null; then
    CODEX_PLUGIN_STATUS=command-error
    return 0
  fi
  if ! jq -e '.installed | type == "array"' "$plugin_json" >/dev/null 2>&1; then
    CODEX_PLUGIN_STATUS=command-error
    return 0
  fi

  plugin_count=$(jq -r --arg id "$DEEPWIND_CODEX_PLUGIN_ID" \
    '[.installed[] | select(.pluginId == $id)] | length' "$plugin_json")
  if [ "$plugin_count" -eq 0 ]; then
    CODEX_PLUGIN_STATUS=plugin-not-enabled
    return 0
  fi
  if [ "$plugin_count" -ne 1 ] || ! jq -e \
    --arg id "$DEEPWIND_CODEX_PLUGIN_ID" \
    --arg source "$CODEX_MARKETPLACE_DIR" '
      any(.installed[];
        .pluginId == $id and
        .marketplaceSource.sourceType == "local" and
        .marketplaceSource.source == $source
      )
    ' "$plugin_json" >/dev/null; then
    CODEX_PLUGIN_STATUS=plugin-source-conflict
    return 0
  fi
  if ! jq -e --arg id "$DEEPWIND_CODEX_PLUGIN_ID" \
    'any(.installed[]; .pluginId == $id and .installed == true and .enabled == true)' \
    "$plugin_json" >/dev/null; then
    CODEX_PLUGIN_STATUS=plugin-disabled
    return 0
  fi
  if ! jq -e --arg id "$DEEPWIND_CODEX_PLUGIN_ID" --arg version "$VERSION" \
    'any(.installed[]; .pluginId == $id and .version == $version)' \
    "$plugin_json" >/dev/null; then
    CODEX_PLUGIN_STATUS=plugin-outdated
    return 0
  fi

  CODEX_PLUGIN_STATUS=enabled
}

print_codex_plugin_status() {
  inspect_codex_plugin
  case "$CODEX_PLUGIN_STATUS" in
    enabled)
      printf 'plugin: enabled (%s %s)\n' "$DEEPWIND_CODEX_PLUGIN_ID" "$VERSION"
      ;;
    cli-unavailable)
      printf '%s\n' \
        'plugin: cli-unavailable (install Codex CLI, then rerun with --enable-codex-plugin)'
      ;;
    marketplace-not-configured|plugin-not-enabled|plugin-disabled)
      printf 'plugin: not-enabled (%s; rerun with --enable-codex-plugin)\n' \
        "$CODEX_PLUGIN_STATUS"
      ;;
    plugin-outdated)
      printf '%s\n' \
        'plugin: outdated (rerun this release with --enable-codex-plugin)'
      return 1
      ;;
    marketplace-conflict)
      printf '%s\n' \
        'plugin: conflict (configured DeepWind marketplace points outside the verified release)'
      return 1
      ;;
    plugin-source-conflict)
      printf '%s\n' \
        'plugin: conflict (installed DeepWind plugin has an unexpected marketplace source)'
      return 1
      ;;
    *)
      printf '%s\n' \
        'plugin: unavailable (Codex lifecycle command failed; rerun --check after repairing Codex CLI)'
      ;;
  esac
  return 0
}

preflight_codex_plugin_enablement() {
  inspect_codex_plugin
  case "$CODEX_PLUGIN_STATUS" in
    enabled|marketplace-not-configured|plugin-not-enabled|plugin-disabled|plugin-outdated)
      return 0
      ;;
    marketplace-conflict)
      die "configured DeepWind marketplace points outside the verified release; preserving it unchanged"
      ;;
    plugin-source-conflict)
      die "installed DeepWind plugin has an unexpected marketplace source; preserving it unchanged"
      ;;
    cli-unavailable)
      die "Codex CLI is required by --enable-codex-plugin"
      ;;
    *)
      die "Codex plugin state could not be inspected; no install or plugin lifecycle change was attempted"
      ;;
  esac
}

enable_codex_plugin() {
  inspect_codex_plugin
  marketplace_added=0
  case "$CODEX_PLUGIN_STATUS" in
    enabled)
      info "Codex plugin already enabled: $DEEPWIND_CODEX_PLUGIN_ID $VERSION"
      return 0
      ;;
    marketplace-conflict)
      die "configured DeepWind marketplace changed during installation; preserving it unchanged"
      ;;
    plugin-source-conflict)
      die "installed DeepWind plugin has an unexpected marketplace source; preserving it unchanged"
      ;;
    cli-unavailable)
      die "Codex CLI is required by --enable-codex-plugin"
      ;;
    command-error)
      die "Codex plugin state changed or became unavailable during installation"
      ;;
    marketplace-not-configured)
      if ! codex plugin marketplace add "$CODEX_MARKETPLACE_DIR" --json >/dev/null 2>&1; then
        die "Codex could not configure the verified DeepWind marketplace"
      fi
      marketplace_added=1
      ;;
    plugin-not-enabled|plugin-disabled|plugin-outdated)
      ;;
    *)
      die "unexpected Codex plugin state: $CODEX_PLUGIN_STATUS"
      ;;
  esac

  if ! codex plugin add deepwind-harness@deepwind --json >/dev/null 2>&1; then
    if [ "$marketplace_added" -eq 1 ]; then
      codex plugin marketplace remove deepwind --json >/dev/null 2>&1 || true
    fi
    die "Codex could not enable the verified DeepWind plugin"
  fi

  inspect_codex_plugin
  [ "$CODEX_PLUGIN_STATUS" = enabled ] \
    || die "Codex did not report the verified DeepWind plugin as enabled"
  info "Codex plugin enabled: $DEEPWIND_CODEX_PLUGIN_ID $VERSION"
}

# ---- lib/bridge-install.sh ----
# shellcheck shell=bash disable=SC2034
# Opt-in, best-effort installation of the DeepWind bridge CLI via npm.
#
# This unit runs only after apply_transaction has committed the signed,
# journaled release install (TRANSACTION_COMMITTED=1). `npm i -g` is a live
# network call outside that trust boundary: it cannot be journaled, verified
# against the release manifest, or rolled back. Every failure path here warns
# and returns success; maybe_install_bridge must never call die and must
# never affect the outcome of the harness install it follows.

BRIDGE_NPM_PACKAGE=@deepwind/bridge
BRIDGE_MIN_NODE_MAJOR=22

maybe_install_bridge() {
  local bridge_node_major
  if ! command -v npm >/dev/null 2>&1; then
    warn "bridge install skipped: npm was not found on PATH (install Node >=$BRIDGE_MIN_NODE_MAJOR, then run: npm i -g $BRIDGE_NPM_PACKAGE)"
    return 0
  fi
  if ! command -v node >/dev/null 2>&1; then
    warn "bridge install skipped: node was not found on PATH (install Node >=$BRIDGE_MIN_NODE_MAJOR, then run: npm i -g $BRIDGE_NPM_PACKAGE)"
    return 0
  fi

  bridge_node_major=$(node -p 'process.versions.node.split(".")[0]' 2>/dev/null) || bridge_node_major=
  case "$bridge_node_major" in
    ''|*[!0-9]*)
      warn "bridge install skipped: could not determine the Node.js version (install Node >=$BRIDGE_MIN_NODE_MAJOR, then run: npm i -g $BRIDGE_NPM_PACKAGE)"
      return 0
      ;;
  esac
  if [ "$bridge_node_major" -lt "$BRIDGE_MIN_NODE_MAJOR" ]; then
    warn "bridge install skipped: Node.js $bridge_node_major is older than the required >=$BRIDGE_MIN_NODE_MAJOR (upgrade Node, then run: npm i -g $BRIDGE_NPM_PACKAGE)"
    return 0
  fi

  info "Installing the DeepWind bridge CLI ($BRIDGE_NPM_PACKAGE)..."
  if npm i -g "$BRIDGE_NPM_PACKAGE" >/dev/null 2>&1; then
    info "DeepWind bridge CLI installed. Next: pm33-bridge login && pm33-bridge register"
  else
    warn "bridge install failed (npm/network); the harness install is unaffected. Retry manually with: npm i -g $BRIDGE_NPM_PACKAGE"
  fi
  return 0
}

# ---- lib/codex-mcp.sh ----
# shellcheck shell=bash
# Explicit, user-mediated Codex MCP onboarding. This unit never reads or writes
# OAuth token storage and never accepts an endpoint from an unsigned source.

DEEPWIND_STAGING_CHANNEL=staging
DEEPWIND_STAGING_ALIAS=deepwind
DEEPWIND_STAGING_URL=https://app.deepwind.ai/mcp

_mcp_info() {
  printf '%s\n' "$*"
}

_mcp_warn() {
  printf 'warning: %s\n' "$*" >&2
}

interactive_tty() {
  [ -c /dev/tty ] || return 1
  (: 2>/dev/null </dev/tty >/dev/tty)
}

verified_staging_endpoint() {
  endpoint_channel=$1
  [ "$endpoint_channel" = "$DEEPWIND_STAGING_CHANNEL" ] || return 1
  [ -n "${MANIFEST_FILE:-}" ] && [ -f "$MANIFEST_FILE" ] || return 1
  command -v jq >/dev/null 2>&1 || return 1

  endpoint_fields=$(jq -er '
    [.channel, .endpoint.alias, .endpoint.url]
    | select(all(.[]; type == "string"))
    | @tsv
  ' "$MANIFEST_FILE" 2>/dev/null) || return 1
  IFS='	' read -r endpoint_manifest_channel endpoint_alias endpoint_url \
    <<< "$endpoint_fields"

  [ "$endpoint_manifest_channel" = "$DEEPWIND_STAGING_CHANNEL" ] \
    && [ "$endpoint_alias" = "$DEEPWIND_STAGING_ALIAS" ] \
    && [ "$endpoint_url" = "$DEEPWIND_STAGING_URL" ]
}

configure_codex_mcp() {
  configure_channel=$1
  configure_consent=$2

  if ! interactive_tty; then
    _mcp_warn 'DeepWind MCP configuration skipped: an interactive terminal is required.'
    return 3
  fi
  if [ "$configure_consent" != yes ]; then
    _mcp_warn 'DeepWind MCP configuration skipped: explicit confirmation was not provided.'
    return 3
  fi
  if ! command -v codex >/dev/null 2>&1; then
    _mcp_warn 'DeepWind MCP configuration skipped: Codex CLI is unavailable.'
    return 4
  fi
  if ! verified_staging_endpoint "$configure_channel"; then
    _mcp_warn 'DeepWind MCP configuration refused: the signed staging endpoint is not allowlisted.'
    return 5
  fi

  _mcp_info 'Configuring DeepWind for the interactive Codex coordinator.'
  if ! codex mcp add "$DEEPWIND_STAGING_ALIAS" \
    --url "$DEEPWIND_STAGING_URL" >/dev/null 2>&1; then
    _mcp_warn 'Codex could not register the DeepWind staging connector; installed files are unchanged.'
    return 6
  fi
  if ! codex mcp login "$DEEPWIND_STAGING_ALIAS" >/dev/null 2>&1; then
    _mcp_warn 'DeepWind OAuth did not complete; rerun with --configure-mcp when ready.'
    return 7
  fi
  _mcp_info 'DeepWind MCP is registered for this interactive Codex user.'
}

maybe_configure_codex_mcp() {
  onboarding_channel=$1
  if ! interactive_tty; then
    configure_codex_mcp "$onboarding_channel" no
    return $?
  fi

  printf '%s\n' \
    'DeepWind MCP channel: staging' \
    'Endpoint: https://app.deepwind.ai/mcp' \
    'OAuth is stored and managed by Codex for this interactive user only.' \
    > /dev/tty
  printf 'Type yes to register and authenticate DeepWind: ' > /dev/tty
  onboarding_consent=
  IFS= read -r onboarding_consent < /dev/tty || onboarding_consent=
  configure_codex_mcp "$onboarding_channel" "$onboarding_consent"
}

# ---- lib/doctor.sh ----
# shellcheck shell=bash disable=SC2154
# Privacy-safe, non-mutating MCP diagnostics. Raw Codex output is consumed by a
# fixed classifier and is never emitted, retained, or written to a log.

classify_codex_mcp_stream() {
  awk '
    BEGIN { exit_status = 0 }
    /^__DEEPWIND_CODEX_EXIT=[0-9]+$/ {
      sub(/^__DEEPWIND_CODEX_EXIT=/, "")
      exit_status = $0 + 0
      next
    }
    {
      line = tolower($0)
      if (line ~ /no[^[:alnum:]]+(deepwind[^[:alnum:]]+)?workspace|workspace[^[:alnum:]]+(is[[:space:]]+)?not[[:space:]-]*configured/) no_workspace = 1
      if (line ~ /oauth|unauthori[sz]ed|authentication|login[[:space:]-]+required|not[[:space:]-]+logged/) oauth = 1
      if (line ~ /session[[:space:]-]+not[[:space:]-]+found|connection|connect[[:space:]-]+failed|unavailable|timed?[[:space:]-]*out|network[[:space:]-]+error/) connection = 1
      if (line ~ /server[[:space:]-]+not[[:space:]-]+found|unknown[[:space:]-]+server|mcp[^[:alnum:]]+not[[:space:]-]+configured/) not_configured = 1
      if (line ~ /enabled|streamable[_ -]?http|https:\/\/dev[.]deepwind[.]ai\/mcp/) configured = 1
    }
    END {
      if (no_workspace) print "no-workspace"
      else if (oauth) print "oauth-required"
      else if (connection) print "connection-unavailable"
      else if (not_configured) print "not-configured"
      else if (configured) print "configured"
      else if (exit_status != 0) print "command-error"
      else print "configured"
    }
  '
}

codex_mcp_status() {
  if ! command -v codex >/dev/null 2>&1; then
    printf '%s\n' cli-unavailable
    return 0
  fi

  {
    codex_status=0
    codex mcp get "$DEEPWIND_STAGING_ALIAS" 2>&1 || codex_status=$?
    printf '__DEEPWIND_CODEX_EXIT=%s\n' "$codex_status"
  } | classify_codex_mcp_stream
}

doctor() {
  doctor_target=$1
  case "$doctor_target" in
    claude)
      printf '%s\n' '{"target":"claude","component":"mcp","status":"not-applicable"}'
      ;;
    codex|both)
      doctor_status=$(codex_mcp_status)
      printf '{"target":"codex","component":"mcp","channel":"staging","status":"%s"}\n' \
        "$doctor_status"
      ;;
    *)
      printf '%s\n' '{"target":"unknown","component":"mcp","status":"not-applicable"}'
      ;;
  esac
  if command -v recovery_state_summary >/dev/null 2>&1 \
    && [ -n "${RECOVERY_STATE_FILE:-}" ]; then
    if recovery_state_summary; then
      printf '{"target":"installer","component":"recovery","status":"%s","count":%s}\n' \
        "$RECOVERY_STATUS" "$RECOVERY_COUNT"
    else
      printf '%s\n' \
        '{"target":"installer","component":"recovery","status":"attention-required","count":0}'
    fi
  else
    printf '%s\n' \
      '{"target":"installer","component":"recovery","status":"unavailable","count":0}'
  fi
  return 0
}

cleanup() {
  status=$?
  trap - EXIT HUP INT TERM
  if [ "${TRANSACTION_COMMITTED:-0}" -ne 1 ]; then
    rollback_transaction
  fi
  release_lock
  if [ "${RETAIN_WORK_DIR:-0}" -ne 1 ] && [ -n "${WORK_DIR:-}" ] && [ -d "$WORK_DIR" ]; then
    find "$WORK_DIR" -depth -type f -exec rm -f {} \;
    find "$WORK_DIR" -depth -type d -exec rmdir {} \; 2>/dev/null || true
  fi
  exit "$status"
}

main() {
  need_command id
  need_command realpath
  need_command stat
  need_command mktemp
  need_command jq
  need_command tar
  need_command awk
  need_command sed
  need_command grep
  need_command curl
  need_command cp
  need_command mv
  need_command chmod
  need_command mkdir
  need_command rmdir
  need_command rm
  need_command find
  need_command df
  need_command sort
  need_command base64
  need_command date
  if ! command -v sha256sum >/dev/null 2>&1; then need_command shasum; fi
  assert_safe_home
  configure_paths
  parse_args "$@"

  WORK_DIR=$(mktemp -d "${TMPDIR:-/tmp}/deepwind-install.XXXXXX") \
    || die "cannot create private staging directory"
  chmod 700 "$WORK_DIR"
  trap cleanup EXIT
  trap 'exit 129' HUP
  trap 'exit 130' INT
  trap 'exit 143' TERM

  prepare_verified_release
  plan_release_install
  case "$MODE" in
    dry-run)
      print_plan
      ;;
    check)
      check_plan
      ;;
    install)
      if [ "$ENABLE_CODEX_PLUGIN" -eq 1 ]; then
        preflight_codex_plugin_enablement
      fi
      apply_transaction
      info "DeepWind $VERSION installed for target: $TARGET"
      merge_gate_summary
      if [ "$ENABLE_CODEX_PLUGIN" -eq 1 ]; then
        enable_codex_plugin
      elif target_selected codex; then
        info "Codex plugin enablement skipped (use --enable-codex-plugin for explicit opt-in)."
      fi
      if [ "$CONFIGURE_MCP" -eq 1 ]; then
        if target_selected codex; then
          if ! maybe_configure_codex_mcp "$CHANNEL"; then
            warn "DeepWind MCP onboarding did not complete; installed harness files remain available."
          fi
          doctor "$TARGET"
        else
          warn "DeepWind MCP configuration skipped: the Codex target was not selected."
        fi
      else
        info "DeepWind MCP configuration skipped (use --configure-mcp for interactive staging OAuth)."
      fi
      if [ "$WITH_BRIDGE" -eq 1 ]; then
        maybe_install_bridge
      fi
      ;;
  esac
}

main "$@"
