#!/usr/bin/env bash
# Build the standalone curl-pipe-bash entry point from reviewed library units.
set -euo pipefail
IFS=$'\n\t'

ROOT=$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd)
OUTPUT=${1:-"$ROOT/deepwind-init.sh"}
TMP="$OUTPUT.tmp.$$"
umask 077
KEYRING="$ROOT/release/keys/trusted-release-keyring.gpg"
if [ "$#" -ge 2 ]; then KEYRING=$2; fi
EMBEDDED_KEYRING=
if [ -s "$KEYRING" ]; then
  EMBEDDED_KEYRING=$(base64 < "$KEYRING" | tr -d '\n')
fi

{
  printf '%s\n' '#!/usr/bin/env bash'
  printf '%s\n' '# Generated by release/build-installer.sh; edit lib/*.sh, not this file.'
  printf '%s\n' 'set -euo pipefail'
  printf '%s\n' "IFS=\$'\\n\\t'"
  printf '%s\n' 'umask 077'
  printf "EMBEDDED_TRUSTED_KEYRING_B64='%s'\n" "$EMBEDDED_KEYRING"
  for unit in state args manifest install-target transaction; do
    printf '\n# ---- lib/%s.sh ----\n' "$unit"
    sed '/^#!/d' "$ROOT/lib/$unit.sh"
  done
  cat <<'EOF'

cleanup() {
  status=$?
  trap - EXIT HUP INT TERM
  if [ "${TRANSACTION_COMMITTED:-0}" -ne 1 ]; then
    rollback_transaction
  fi
  release_lock
  if [ "${RETAIN_WORK_DIR:-0}" -ne 1 ] && [ -n "${WORK_DIR:-}" ] && [ -d "$WORK_DIR" ]; then
    find "$WORK_DIR" -depth -type f -exec rm -f {} \;
    find "$WORK_DIR" -depth -type d -exec rmdir {} \; 2>/dev/null || true
  fi
  exit "$status"
}

main() {
  need_command id
  need_command realpath
  need_command stat
  need_command mktemp
  need_command jq
  need_command tar
  need_command awk
  need_command sed
  need_command grep
  need_command curl
  need_command cp
  need_command mv
  need_command chmod
  need_command mkdir
  need_command rmdir
  need_command rm
  need_command find
  need_command df
  need_command sort
  need_command base64
  need_command date
  if ! command -v sha256sum >/dev/null 2>&1; then need_command shasum; fi
  assert_safe_home
  configure_paths
  parse_args "$@"

  WORK_DIR=$(mktemp -d "${TMPDIR:-/tmp}/deepwind-install.XXXXXX") \
    || die "cannot create private staging directory"
  chmod 700 "$WORK_DIR"
  trap cleanup EXIT
  trap 'exit 129' HUP
  trap 'exit 130' INT
  trap 'exit 143' TERM

  prepare_verified_release
  plan_release_install
  case "$MODE" in
    dry-run)
      print_plan
      ;;
    check)
      check_plan
      ;;
    install)
      apply_transaction
      info "DeepWind $VERSION installed for target: $TARGET"
      ;;
  esac
}

main "$@"
EOF
} > "$TMP"

chmod 755 "$TMP"
mv -f "$TMP" "$OUTPUT"
